### ISSUE TITLE
proposal_success.html typo

### ISSUE THREAD

**Issue by Aprillion** [pyvec/cz.pycon.org-2018#12]
I can't edit directly on github web (which would create a fork + PR automatically) because "You must be on a branch to make or propose changes to this file" and I am too lazy to clone the repo :(

There is a typo on https://github.com/pyvec/cz.pycon.org-2018/blob/1f7a372a648759b1a209b47c7e7af44130ebdec4/pyconcz_2018/templates/proposals/proposal_success.html "We're received your proposal"

should be "We've received your proposal"

**Comment by starenka** [comment]
Cheers! https://github.com/pyvec/cz.pycon.org-2018/commit/0faa1c490f74ffb6efa01e38ff52e7fa21fe661d

**Comment by honzajavorek** [comment]
@Aprillion "You must be on a branch to make or propose changes to this file"

This is something I experience when I find a file by search and it's displayed on a particular commit:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/283441/35474678-00d5c88c-0392-11e8-843a-8fb00b7c7499.png">

When I click, then see top left corner - the drop down shows a specific commit:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/283441/35474697-16505d9e-0392-11e8-8a33-5f4c5cff11f4.png">

And it's not possible to do edits:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/283441/35474702-2d2c40fa-0392-11e8-8269-03a4bc7f16a9.png">

But when you switch to master:

<img width="166" alt="image" src="https://user-images.githubusercontent.com/283441/35474703-37e703e0-0392-11e8-8a5e-bf85c92d6074.png">

Suddenly it's possible:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/283441/35474705-44e8fb3e-0392-11e8-93d4-f462ce49546c.png">

Does it work for you?

**Comment by Aprillion** [comment]
@honzajavorek that works, thanks! didn't know I was on particular commit and not on master and no idea how it happened - when I went all the way from pycon.cz webpage to github to the concrete file again, I ended up on master branch. oh well, at least I will know if I notice another typo :)
