### ISSUE TITLE
Proposal forms tweaks

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2018#25]
# Better order of fields + divide them into 2 sections (their names are TBD)

[Public information]
What’s your name? 
What is the title of your talk? 
Tell the audience about your talk in 1–3 paragraphs (90–200 words) 
Language
Difficulty
Why are you the right person to talk about the topic you chose?
Your photo (not an illustration nor avatar)
Twitter handle 
GitHub username 

[Non-public information]
Got a video? 
Your email address
I need financial aid to make this talk possible
Details about required financial aid 
Anything else you want to tell us?

# Better microcopy

-  _What is the title of your talk?_ and _Tell the audience about your talk in 1–3 paragraphs (90–200 words):_
- _English (preffered)_ => _English (preffered by PyCon CZ)_
- _If you already have a recording of you giving a talk, you can paste the link here._ => _If you have a link to a publicly available recording of you giving a talk. Will be used in the decision process._
- _It will be published on the website. Ideal photo is: a head shot, shows only you, has no “filters” applied and is as large and uncompressed as possible. We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style._ => _Ideal photo is as large (really there's no limit, please no 128 × 128 px, even 1000 × 1000 px isn’t too much) and as uncompressed as possible, is a head shot, doesn’t show other people and has no “filters” applied. We might crop it and change contrast, brightness etc. to fit PyCon CZ visual style._
- Try better to explain what is required for bio.

**Comment by hroncok** [comment]
Why are you the right person to talk about the topic you chose?
Who are you, tel us something about you.

We could add both questions and than combine the bio used on the website ourselves. We edit all the bios anyway, so this would just give us more material.

**Comment by benabraham** [comment]
moved to 2019
