### ISSUE TITLE
proposals/emails/*.tpl need to be updated

### ISSUE THREAD

**Issue by benabraham** [pyvec/cz.pycon.org-2018#31]
They're just copies from 2017.

**Comment by honzajavorek** [comment]
I’m wondering whether we can move them elsewhere (different repo), as this
way this issue will be relevant every year and the templates need to be
moved every year.

**Comment by benabraham** [comment]
Or they might be rewritten to be year independent. 🤔 Or take year dynamically from CfP end date or something.

And we have many year dependent templates there anyway, so moving this out doesn't make much sense to me.

**Comment by starenka** [comment]
AFAIK the emails are sent via mailchimp by hand, so I'm not sure this
template has any value. I did generate all email bodies to text file and
bara sent it via mailchimp.....

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]
